name: WildFly Build

on:
  push:
  workflow_dispatch:
    inputs:
      os:
        description: "Runner OS"
        required: true
        default: "ubuntu-latest"
        type: choice
        options:
          - "ubuntu-latest"
          - "windows-latest"
      javaVersion:
        description: "Java Version"
        required: true
        default: "11"
        type: choice
        options:
          - "11"
          - "17"

jobs:
  
  quick-build:
    name: WildFly Build -Dquickly
    runs-on: ${{ matrix.os }}
    timeout-minutes: 300
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Clear any possible SNAPSHOT dependencies in the local maven repository
        run: |
          LOCAL_REPO="$HOME/.m2/repository"
          echo "Cleaning SNAPSHOTS from $LOCAL_REPO"
          if [ -d "$LOCAL_REPO" ]; then find "$LOCAL_REPO" -name "*SNAPSHOT*" | xargs -I {} rm -rfv "{}"; fi
        shell: bash
      #- name: Check out NonDex
      #  uses: actions/checkout@master
      #  with:
      #    repository: TestingResearchIllinois/NonDex
      #    path: ./NonDex
      #    submodules: recursive
      #- name: Install NonDex
      #  run: |
       #   ls
        #  cd ./NonDex
         # mvn install
          #cd ..
          #cd ./dist
          #cat pom.xml
          #pwd
      #
      #- name: Run all tests
      #  run: mvn nondex:nondex -DnondexRuns=20
      #- name: install project
      #  run: mvn install
      - name: Run tests
        run: mvn install -DallTests

      




